import Link from "next/link";
import { ArrowLeft, Send } from "lucide-react";
import { requestPortalAccess } from "@/app/portal-actions";
import { BrandLogo } from "@/components/brand-logo";

const input = "mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3 text-base text-slate-950 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100";

export default function PortalAccessPage() {
  return <main className="min-h-[100dvh] bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,.14),transparent_30%),radial-gradient(circle_at_bottom_right,rgba(139,92,246,.15),transparent_35%),#050816] p-4 sm:p-8"><div className="mx-auto max-w-3xl"><Link href="/portal" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-white"><ArrowLeft className="h-4 w-4" />Back to sign in</Link><div className="mt-6 rounded-[30px] bg-white p-6 shadow-2xl sm:p-9"><BrandLogo /><p className="mt-8 text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Portal access</p><h1 className="mt-3 text-3xl font-semibold text-slate-950 sm:text-4xl">Request the right workspace for your role.</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-600">Clients receive project visibility and change requests. Employees receive assignments, tasks, reviews, and daily updates. Admin access is approved manually.</p><form action={requestPortalAccess} className="mt-8 grid gap-5"><input type="hidden" name="returnTo" value="/portal" /><div className="grid gap-5 sm:grid-cols-2"><label><span className="text-sm font-semibold text-slate-700">Full name</span><input name="fullName" autoComplete="name" required className={input} /></label><label><span className="text-sm font-semibold text-slate-700">Phone number</span><input name="phone" type="tel" autoComplete="tel" required className={input} /></label></div><div className="grid gap-5 sm:grid-cols-2"><label><span className="text-sm font-semibold text-slate-700">Email</span><input name="email" type="email" autoComplete="email" required className={input} /></label><label><span className="text-sm font-semibold text-slate-700">Company name</span><input name="companyName" autoComplete="organization" className={input} /></label></div><label><span className="text-sm font-semibold text-slate-700">Account type</span><select name="accountType" required className={input} defaultValue="Client account"><option>Client account</option><option>Employee account</option><option>Admin account</option></select></label><label><span className="text-sm font-semibold text-slate-700">How should HouseOfDev help?</span><textarea name="message" className={`${input} min-h-28 py-3`} placeholder="Tell us which project or role this access is for." /></label><label className="hidden">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><button type="submit" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-950 px-6 text-sm font-bold text-white hover:bg-blue-700"><Send className="h-4 w-4" />Send access request</button></form></div></div></main>;
}
